name: post_merge_s3_action

# Any merged PR becomes a push to master/main
on:
  push:
    branches:
      - test

jobs:
  post_merge_s3_job:
    name: post_merge_s3_job

    runs-on: ubuntu-latest

    steps:
      # checkout our private actions repo containing the action to run
      - name: Checkout GitHub Actions Repo
        uses: actions/checkout@v2
        with:
          repository: insurely/insurely_ui_test_actions
          token: ${{ secrets.GIT_HUB_TOKEN }} # stored in GitHub secrets
          path: .github/actions/screenshot-action

      - name: Run post merge s3 update
        uses: ./.github/actions/screenshot-action/post_merge_s3_action
        with:
          application: test_runner # Specify frontend app
          environment: localhost # At the moment the testing tool only supports test
          # The below arguments must be stored in Github secrets
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-bucket-base-name: ${{ secrets.AWS_BUCKET_BASE_NAME }}
